<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class User2_model extends CI_Model
{

    public $table = 'public.user';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id,user,auth_key,password_hash,password_reset_token,email,status,created_at,updated_at,picture,updated_by');
        $this->datatables->from('public.user');
        //add this line for join
        //$this->datatables->join('table2', 'public.user.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('user2/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-success', 'title' => 'Lihat Detail Data'))." 
            ".anchor(site_url('user2/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-warning', 'title' => 'Ubah Data'))." 
                ".anchor(site_url('user2/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger hapus" title="Hapus Data"'), 'id');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
       $this->db->like("cast(id as text)", $q);
		$this->db->or_like("cast(id as text)", $q);
		$this->db->or_like("cast(user as text)", $q);
		$this->db->or_like("cast(auth_key as text)", $q);
		$this->db->or_like("cast(password_hash as text)", $q);
		$this->db->or_like("cast(password_reset_token as text)", $q);
		$this->db->or_like("cast(email as text)", $q);
		$this->db->or_like("cast(status as text)", $q);
		$this->db->or_like("cast(created_at as text)", $q);
		$this->db->or_like("cast(updated_at as text)", $q);
		$this->db->or_like("cast(picture as text)", $q);
		$this->db->or_like("cast(updated_by as text)", $q);
		$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like("cast(id as text)", $q);
		$this->db->or_like("cast(id as text)", $q);
		$this->db->or_like("cast(user as text)", $q);
		$this->db->or_like("cast(auth_key as text)", $q);
		$this->db->or_like("cast(password_hash as text)", $q);
		$this->db->or_like("cast(password_reset_token as text)", $q);
		$this->db->or_like("cast(email as text)", $q);
		$this->db->or_like("cast(status as text)", $q);
		$this->db->or_like("cast(created_at as text)", $q);
		$this->db->or_like("cast(updated_at as text)", $q);
		$this->db->or_like("cast(picture as text)", $q);
		$this->db->or_like("cast(updated_by as text)", $q);
		$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file User2_model.php */
/* Location: ./application/models/User2_model.php */
/* Please DO NOT modify this information : */
/* Generated by CRUDV2 Generator For AdminLTE Template 2024-11-12 04:42:50 */